# Generated by Django 5.2.4 on 2025-08-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerSupportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('date', models.DateField(verbose_name='date')),
                ('support_type', models.CharField(max_length=100, verbose_name='support type')),
                ('is_successful', models.BooleanField(default=True, verbose_name='is successful')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_activities', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farmer Support Activity',
                'verbose_name_plural': 'Farmer Support Activities',
                'ordering': ['-date'],
            },
        ),
    ]
