# Generated by Django 5.2.4 on 2025-08-29 13:04

import django.utils.timezone
import farmers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_alter_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='interview_date',
            field=models.DateField(default=farmers.models.today_utc_plus_2, verbose_name='Date of interview'),
        ),
    ]
