# Generated by Django 5.2.4 on 2025-08-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0008_farmerstory_video'),
        ('farmers', '000X_farm_sponsor'),
    ]

    operations = [
    ]
