# Generated by Django 5.2.4 on 2025-08-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0009_merge_0008_farmerstory_video_000X_farm_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='sponsorship_description',
            field=models.TextField(blank=True, help_text='Public info for sponsors', verbose_name='Sponsorship Description'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sponsorship_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target amount for farm sponsorship', max_digits=10, null=True, verbose_name='Sponsorship Goal (USD)'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sponsorship_is_active',
            field=models.BooleanField(default=False, help_text='Is this farm open for sponsorship?', verbose_name='Sponsorship Active'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sponsorship_logo',
            field=models.ImageField(blank=True, null=True, upload_to='farm_sponsorships/logos/', verbose_name='Sponsorship Logo'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sponsorship_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount received for sponsorship', max_digits=10, verbose_name='Sponsorship Received (USD)'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sponsorship_video',
            field=models.FileField(blank=True, help_text='Optional video for sponsors', null=True, upload_to='farm_sponsorships/videos/', verbose_name='Sponsorship Video'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farmsponsorship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
