# Generated by Django 5.2.5 on 2025-09-01 17:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0011_farm_sponsorship_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='sponsorship_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Public info for sponsors', verbose_name='Sponsorship Description'),
        ),
        migrations.AlterField(
            model_name='farmerstory',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='farmsponsorship',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
