# Generated by Django 5.2.4 on 2025-09-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0014_alter_farmer_bio_alter_farmer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='sector_district',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='village_cell',
        ),
        migrations.AddField(
            model_name='farmer',
            name='cell',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cell'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(blank=True, max_length=100, verbose_name='Village'),
        ),
    ]
