# Generated by Django 5.2.6 on 2025-12-17 04:42

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', ckeditor.fields.RichTextField(help_text='Event description')),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                ('location', models.CharField(help_text='Event location', max_length=255)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Event status', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Event image or banner', null=True, upload_to='events/')),
                ('video', models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='events/videos/')),
                ('pinned', models.BooleanField(default=False, help_text='Pin this event to keep it at the top', verbose_name='Pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(blank=True, help_text='Event organizer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
