# Generated by Django 5.2.4 on 2025-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(help_text='Event description', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fr',
            field=models.TextField(help_text='Event description', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_rw',
            field=models.TextField(help_text='Event description', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(help_text='Event location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_fr',
            field=models.CharField(help_text='Event location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_rw',
            field=models.CharField(help_text='Event location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(help_text='Event title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fr',
            field=models.CharField(help_text='Event title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_rw',
            field=models.CharField(help_text='Event title', max_length=200, null=True),
        ),
    ]
