# Generated by Django 5.2.5 on 2025-09-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_description_alter_event_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_rw',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_rw',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_rw',
        ),
    ]
