# Generated by Django 5.2.6 on 2025-10-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin this event to keep it at the top', verbose_name='Pinned'),
        ),
    ]
