# Generated by Django 5.2.5 on 2025-12-17 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('title', models.CharField(max_length=100, verbose_name='Title/Role')),
                ('photo', models.ImageField(upload_to='team_photos/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, verbose_name='Short Bio')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter Link')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram Link')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube Link')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('province_district', models.CharField(blank=True, max_length=100, verbose_name='Province / District')),
                ('donation_frequency', models.CharField(choices=[('one_time', 'One-time Donation'), ('recurring', 'Monthly / Recurring Donation')], default='one_time', max_length=20, verbose_name='Donation Frequency')),
                ('currency', models.CharField(choices=[('RWF', 'RWF'), ('USD', 'USD'), ('EUR', 'EUR'), ('KES', 'KES'), ('UGX', 'UGX'), ('Other', 'Other')], default='RWF', max_length=10, verbose_name='Currency')),
                ('donation_mode', models.CharField(choices=[('mobile_money', 'Mobile Money (MTN / Airtel)'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('cash', 'Cash'), ('other', 'Other')], default='mobile_money', max_length=20, verbose_name='Mode of Donation')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Transaction Reference Number')),
                ('purpose', models.CharField(blank=True, choices=[('training', 'Training Programs'), ('community', 'Community Projects'), ('equipment', 'Equipment / Materials'), ('general', 'General Support (where most needed)')], max_length=20, verbose_name='Purpose of Donation')),
                ('public_acknowledgement', models.BooleanField(default=True, verbose_name='Publicly acknowledge as donor?')),
                ('communication_opt_in', models.BooleanField(default=True, verbose_name='Receive updates about the initiative?')),
                ('declaration', models.BooleanField(default=False, verbose_name='I confirm this donation is made willingly.')),
                ('donor_signature', models.CharField(blank=True, max_length=100, verbose_name='Full Name of Donor (as signature)')),
                ('signature_date', models.DateField(blank=True, null=True, verbose_name='Date of signature')),
                ('donor_name', models.CharField(blank=True, max_length=100, verbose_name='Donor Name')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Donor Email')),
                ('amount', models.FloatField(verbose_name='Amount (RWF)')),
                ('donation_type', models.CharField(choices=[('general', 'General Initiative Support'), ('tree', 'Sponsor a Coffee Tree'), ('tour', 'Tourism Experience')], max_length=10, verbose_name='Donation Type')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('payment_status', models.CharField(default='pending', max_length=20, verbose_name='Payment Status')),
                ('receipt_sent', models.BooleanField(default=False, verbose_name='Receipt Sent')),
                ('farmer', models.ForeignKey(blank=True, help_text='If supporting a farmer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.farmer')),
                ('tree', models.ForeignKey(blank=True, help_text='If sponsoring a tree', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.tree')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
