# Generated by Django 5.2.4 on 2025-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_en',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_fr',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_rw',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_en',
            field=models.CharField(max_length=200, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_rw',
            field=models.CharField(max_length=200, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='subject'),
        ),
    ]
