# Generated by Django 5.2.4 on 2025-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='communication_opt_in',
            field=models.BooleanField(default=True, verbose_name='Receive updates about the initiative?'),
        ),
        migrations.AddField(
            model_name='donation',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('RWF', 'RWF'), ('USD', 'USD'), ('EUR', 'EUR'), ('KES', 'KES'), ('UGX', 'UGX'), ('Other', 'Other')], default='RWF', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='donation',
            name='declaration',
            field=models.BooleanField(default=False, verbose_name='I confirm this donation is made willingly.'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_frequency',
            field=models.CharField(choices=[('one_time', 'One-time Donation'), ('recurring', 'Monthly / Recurring Donation')], default='one_time', max_length=20, verbose_name='Donation Frequency'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_mode',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money (MTN / Airtel)'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('cash', 'Cash'), ('other', 'Other')], default='mobile_money', max_length=20, verbose_name='Mode of Donation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_signature',
            field=models.CharField(blank=True, max_length=100, verbose_name='Full Name of Donor (as signature)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='donation',
            name='province_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province / District'),
        ),
        migrations.AddField(
            model_name='donation',
            name='public_acknowledgement',
            field=models.BooleanField(default=True, verbose_name='Publicly acknowledge as donor?'),
        ),
        migrations.AddField(
            model_name='donation',
            name='purpose',
            field=models.CharField(blank=True, choices=[('training', 'Training Programs'), ('community', 'Community Projects'), ('equipment', 'Equipment / Materials'), ('general', 'General Support (where most needed)')], max_length=20, verbose_name='Purpose of Donation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of signature'),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transaction Reference Number'),
        ),
    ]
