# Generated by Django 5.2.6 on 2025-09-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contact_message_en_remove_contact_message_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('title', models.CharField(max_length=100, verbose_name='Title/Role')),
                ('photo', models.ImageField(upload_to='team_photos/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, verbose_name='Short Bio')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter Link')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram Link')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube Link')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(verbose_name='Amount (RWF)'),
        ),
    ]
