# Generated by Django 5.2.5 on 2025-12-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False, help_text='Pin this item to keep it at the top of the gallery', verbose_name='pinned')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='image')),
                ('video', models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='gallery/videos/', verbose_name='video')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-pinned', '-uploaded_at'],
            },
        ),
    ]
