# Generated by Django 5.2.5 on 2025-09-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='description_rw',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title_rw',
        ),
    ]
