# Generated by Django 5.2.6 on 2025-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-pinned', '-uploaded_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin this item to keep it at the top of the gallery', verbose_name='pinned'),
        ),
    ]
