# Generated by Django 5.2.4 on 2025-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_volunteerapplication_areas_of_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='areas_of_interest',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Areas of Interest'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='National ID/Passport No.'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Why do you want to volunteer with us?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='province_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province/District'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='sector_cell_village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector/Cell/Village'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='signature_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signature (Full Name)'),
        ),
    ]
