# Generated by Django 5.2.4 on 2025-08-31 17:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_alter_volunteerapplication_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='areas_of_interest',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='availability_times',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='other_interest',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='province_district',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='skills_experience',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability_full_time',
            field=models.BooleanField(default=False, verbose_name='Full-time'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability_part_time',
            field=models.BooleanField(default=False, verbose_name='Part-time'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability_specific_dates',
            field=models.CharField(blank=True, max_length=100, verbose_name='Specific dates'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability_weekdays',
            field=models.CharField(blank=True, max_length=100, verbose_name='Weekdays (specify times)'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability_weekends',
            field=models.BooleanField(default=False, verbose_name='Weekends'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='interest_admin_support',
            field=models.BooleanField(default=False, verbose_name='Administrative Support'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='interest_community_outreach',
            field=models.BooleanField(default=False, verbose_name='Community Outreach'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='interest_environmental',
            field=models.BooleanField(default=False, verbose_name='Environmental Activities (tree planting, farming, etc.)'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='interest_event_support',
            field=models.BooleanField(default=False, verbose_name='Event Support'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='interest_fundraising',
            field=models.BooleanField(default=False, verbose_name='Fundraising & Campaigns'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='interest_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='interest_training_mentorship',
            field=models.BooleanField(default=False, verbose_name='Training & Mentorship'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='province',
            field=models.CharField(default='', max_length=50, verbose_name='Province/District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='skills',
            field=models.TextField(default='', verbose_name='Relevant Skills & Experience'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='country',
            field=models.CharField(default='', max_length=50, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 8, 31), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='Emergency Contact Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=30, verbose_name='Emergency Contact Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_relationship',
            field=models.CharField(default='', max_length=50, verbose_name='Relationship'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='id_number',
            field=models.CharField(default='', max_length=16, verbose_name='National ID/Passport No.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='motivation',
            field=models.TextField(default='', verbose_name='Motivation Letter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteeropportunity'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='sector_cell_village',
            field=models.CharField(default='', max_length=100, verbose_name='Sector/Cell/Village'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='signature_date',
            field=models.DateField(default='2020-01-01', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='signature_name',
            field=models.CharField(default='', max_length=100, verbose_name='Signature (Full Name)'),
            preserve_default=False,
        ),
    ]
