# Generated by Django 5.2.5 on 2025-09-02 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0012_remove_volunteerapplication_reference_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatraining',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='expected_skills',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='What skills or knowledge do you expect to gain?'),
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='motivation',
            field=ckeditor.fields.RichTextField(verbose_name='Why do you want to attend this training?'),
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='skills_experience',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Relevant Skills or Experience'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='motivation',
            field=ckeditor.fields.RichTextField(verbose_name='Motivation Letter'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='skills',
            field=ckeditor.fields.RichTextField(verbose_name='Relevant Skills & Experience'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='skills_required',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='skills required'),
        ),
    ]
