# Generated by Django 5.2.5 on 2025-09-02 06:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0013_alter_baristatraining_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatraining',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='barista_training_banners/', verbose_name='Banner or pullup'),
        ),
        migrations.AlterField(
            model_name='baristatraining',
            name='date',
            field=models.DateField(verbose_name='Training date'),
        ),
        migrations.AlterField(
            model_name='baristatraining',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='baristatraining',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barista_training/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='baristatraining',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='baristatraining',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='baristatraining',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='baristatraining',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='barista_training/videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Application date'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (jpg, png, webp, max 5MB)', null=True, upload_to='volunteer_opportunities/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='max_volunteers',
            field=models.PositiveIntegerField(default=1, verbose_name='Maximum volunteers'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='skills_required',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Skills required'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='volunteer_opportunities/videos/', verbose_name='Video'),
        ),
    ]
