# Generated by Django 5.2.6 on 2025-09-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0016_alter_baristatrainingapplication_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=100, verbose_name='Languages Spoken'),
        ),
    ]
