# Generated by Django 5.2.6 on 2025-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0017_alter_baristatrainingapplication_languages_spoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='skills_experience',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills', max_length=200, verbose_name='Relevant Skills or Experience'),
        ),
    ]
