# Generated by Django 5.2.6 on 2025-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0020_alter_baristatrainingapplication_expected_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Expected Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Motivation')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Skill')),
            ],
        ),
        migrations.RemoveField(
            model_name='baristatrainingapplication',
            name='expected_skills',
        ),
        migrations.RemoveField(
            model_name='baristatrainingapplication',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='baristatrainingapplication',
            name='skills_experience',
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='expected_skills',
            field=models.ManyToManyField(blank=True, related_name='applications', to='volunteers.expectedskill', verbose_name='What skills or knowledge do you expect to gain?'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='motivation',
            field=models.ManyToManyField(blank=True, related_name='applications', to='volunteers.motivation', verbose_name='Why do you want to attend this training?'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='skills_experience',
            field=models.ManyToManyField(blank=True, related_name='applications', to='volunteers.skill', verbose_name='Relevant Skills or Experience'),
        ),
    ]
