# Generated by Django 5.2.6 on 2025-12-19 12:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the newsletter (max 300 characters)', max_length=300, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF or document file', null=True, upload_to='newsletter_documents/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional detailed content', null=True, verbose_name='content'),
        ),
    ]
