# Generated by Django 5.2.4 on 2025-08-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_merge_0003_alter_newsletter_id_0003_newsletter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='image',
        ),
        migrations.CreateModel(
            name='NewsletterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsletter_images/', verbose_name='image')),
                ('video', models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='newsletter_videos/', verbose_name='video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='newsletter.newsletter')),
            ],
            options={
                'verbose_name': 'Newsletter Media',
                'verbose_name_plural': 'Newsletter Media',
                'ordering': ['created_at'],
            },
        ),
    ]
