# Generated by Django 5.2.5 on 2025-09-02 04:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_newsletter_image_newslettermedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
    ]
