# Generated by Django 4.2.7 on 2025-07-30 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.CharField(max_length=50, unique=True, verbose_name='Tree ID')),
                ('species', models.CharField(choices=[('coffee', 'Coffee Plant'), ('avocado', 'Avocado'), ('banana', 'Banana'), ('grevillea', 'Grevillea'), ('eucalyptus', 'Eucalyptus')], max_length=100, verbose_name='Species')),
                ('planted_date', models.DateField(verbose_name='Planted Date')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trees/', verbose_name='Photo')),
                ('co2_offset', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CO₂ Offset (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trees', to='farmers.farmer', verbose_name='Farmer')),
                ('planted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planted_trees', to=settings.AUTH_USER_MODEL, verbose_name='Planted By')),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
                'ordering': ['-planted_date'],
            },
        ),
    ]
