# Generated by Django 5.2.5 on 2025-12-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePlantingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Planting (Optional)')),
                ('agreement', models.BooleanField(default=False, verbose_name='I commit to ensuring the planted trees are cared for and maintained.')),
                ('tree_type', models.CharField(choices=[('mango', 'Mango'), ('coffee', 'Coffee'), ('eucalyptus', 'Eucalyptus'), ('avocado', 'Avocado'), ('other', 'Other')], max_length=32, verbose_name='Tree Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity (Number of Trees)')),
                ('country', models.CharField(max_length=64, verbose_name='Country')),
                ('province', models.CharField(max_length=64, verbose_name='Province')),
                ('district', models.CharField(max_length=64, verbose_name='District')),
                ('sector', models.CharField(max_length=64, verbose_name='Sector')),
                ('cell', models.CharField(max_length=64, verbose_name='Cell')),
                ('village', models.CharField(max_length=64, verbose_name='Village')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('planting_date', models.DateField(verbose_name='Planting Date')),
                ('contribution_type', models.CharField(choices=[('self', 'I will provide and plant the trees myself 🌱'), ('donate', 'I will donate/provide trees for planting 🌳'), ('support', 'I will support others to plant trees (financial or logistical support) 💚')], max_length=32, verbose_name='Contribution Type')),
                ('full_name', models.CharField(max_length=128, verbose_name='Your Full Name')),
                ('contact', models.CharField(max_length=128, verbose_name='Email Address / Phone Number')),
            ],
            options={
                'verbose_name': 'Tree Planting Submission',
                'verbose_name_plural': 'Tree Planting Submissions',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False, help_text='Pin this tree to keep it at the top', verbose_name='Pinned')),
                ('tree_id', models.CharField(max_length=50, unique=True, verbose_name='Tree ID')),
                ('species', models.CharField(choices=[('coffee', 'Coffee Plant'), ('avocado', 'Avocado'), ('banana', 'Banana'), ('grevillea', 'Grevillea'), ('eucalyptus', 'Eucalyptus')], max_length=100, verbose_name='Species')),
                ('planted_date', models.DateField(verbose_name='Planted Date')),
                ('location', models.CharField(blank=True, choices=[('Gasabo', 'Gasabo'), ('Kicukiro', 'Kicukiro'), ('Nyarugenge', 'Nyarugenge'), ('Bugesera', 'Bugesera'), ('Gatsibo', 'Gatsibo'), ('Kayonza', 'Kayonza'), ('Kirehe', 'Kirehe'), ('Ngoma', 'Ngoma'), ('Nyagatare', 'Nyagatare'), ('Rwamagana', 'Rwamagana'), ('Burera', 'Burera'), ('Gakenke', 'Gakenke'), ('Gicumbi', 'Gicumbi'), ('Musanze', 'Musanze'), ('Rulindo', 'Rulindo'), ('Gisagara', 'Gisagara'), ('Huye', 'Huye'), ('Kamonyi', 'Kamonyi'), ('Muhanga', 'Muhanga'), ('Nyamagabe', 'Nyamagabe'), ('Nyanza', 'Nyanza'), ('Ruhango', 'Ruhango'), ('Karongi', 'Karongi'), ('Ngororero', 'Ngororero'), ('Nyabihu', 'Nyabihu'), ('Rubavu', 'Rubavu'), ('Rusizi', 'Rusizi'), ('Rutsiro', 'Rutsiro')], max_length=255, verbose_name='Location')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude')),
                ('planted_by', models.CharField(blank=True, max_length=128, verbose_name='Planted By')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trees/', verbose_name='Photo')),
                ('video', models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='trees/videos/', verbose_name='Video')),
                ('co2_offset', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CO₂ Offset (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trees', to='farmers.farmer', verbose_name='Farmer')),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
            },
        ),
    ]
