# Generated by Django 5.2.4 on 2025-08-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_tree_latitude_tree_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='trees/videos/', verbose_name='Video'),
        ),
    ]
