# Generated by Django 5.2.4 on 2025-09-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_tree_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePlantingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_type', models.CharField(choices=[('mango', 'Mango'), ('coffee', 'Coffee'), ('eucalyptus', 'Eucalyptus'), ('avocado', 'Avocado'), ('other', 'Other')], max_length=32, verbose_name='Tree Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity (Number of Trees)')),
                ('country', models.CharField(max_length=64, verbose_name='Country')),
                ('province', models.CharField(max_length=64, verbose_name='Province')),
                ('district', models.CharField(max_length=64, verbose_name='District')),
                ('sector', models.CharField(max_length=64, verbose_name='Sector')),
                ('cell', models.CharField(max_length=64, verbose_name='Cell')),
                ('village', models.CharField(max_length=64, verbose_name='Village')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('planting_date', models.DateField(verbose_name='Planting Date')),
                ('contribution_type', models.CharField(choices=[('self', 'I will provide and plant the trees myself 🌱'), ('donate', 'I will donate/provide trees for planting 🌳'), ('support', 'I will support others to plant trees (financial or logistical support) 💚')], max_length=32, verbose_name='Contribution Type')),
                ('full_name', models.CharField(max_length=128, verbose_name='Your Full Name')),
                ('contact', models.CharField(max_length=128, verbose_name='Email Address / Phone Number')),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Planting (Optional)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tree_planting_submissions/', verbose_name='Upload a Photo (Optional)')),
                ('agreement', models.BooleanField(verbose_name='Agreement/Consent')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Tree Planting Submission',
                'verbose_name_plural': 'Tree Planting Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
