# Generated by Django 5.2.5 on 2025-09-02 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_treeplantingsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeplantingsubmission',
            name='reason',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Reason for Planting (Optional)'),
        ),
    ]
