# Generated by Django 5.2.5 on 2025-09-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_alter_treeplantingsubmission_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treeplantingsubmission',
            options={'verbose_name': 'Tree Planting Submission', 'verbose_name_plural': 'Tree Planting Submissions'},
        ),
        migrations.RemoveField(
            model_name='treeplantingsubmission',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='treeplantingsubmission',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='treeplantingsubmission',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='treeplantingsubmission',
            name='submitted_at',
        ),
    ]
