# Generated by Django 5.2.6 on 2025-09-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_alter_treeplantingsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='planted_by_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Planted By (Name)'),
        ),
    ]
