# Generated by Django 5.2.6 on 2025-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_remove_tree_planted_by_name_alter_tree_planted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeplantingsubmission',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='I commit to ensuring the planted trees are cared for and maintained.'),
        ),
        migrations.AddField(
            model_name='treeplantingsubmission',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Planting (Optional)'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='location',
            field=models.CharField(blank=True, choices=[('Gasabo', 'Gasabo'), ('Kicukiro', 'Kicukiro'), ('Nyarugenge', 'Nyarugenge'), ('Bugesera', 'Bugesera'), ('Gatsibo', 'Gatsibo'), ('Kayonza', 'Kayonza'), ('Kirehe', 'Kirehe'), ('Ngoma', 'Ngoma'), ('Nyagatare', 'Nyagatare'), ('Rwamagana', 'Rwamagana'), ('Burera', 'Burera'), ('Gakenke', 'Gakenke'), ('Gicumbi', 'Gicumbi'), ('Musanze', 'Musanze'), ('Rulindo', 'Rulindo'), ('Gisagara', 'Gisagara'), ('Huye', 'Huye'), ('Kamonyi', 'Kamonyi'), ('Muhanga', 'Muhanga'), ('Nyamagabe', 'Nyamagabe'), ('Nyanza', 'Nyanza'), ('Ruhango', 'Ruhango'), ('Karongi', 'Karongi'), ('Ngororero', 'Ngororero'), ('Nyabihu', 'Nyabihu'), ('Rubavu', 'Rubavu'), ('Rusizi', 'Rusizi'), ('Rutsiro', 'Rutsiro')], max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
        ),
    ]
