# Generated by Django 5.2.6 on 2025-10-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_treeplantingsubmission_agreement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'verbose_name': 'Tree', 'verbose_name_plural': 'Trees'},
        ),
        migrations.AddField(
            model_name='tree',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin this tree to keep it at the top', verbose_name='Pinned'),
        ),
    ]
