# Generated by Django 4.2.7 on 2025-07-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='One Cup One Tree', max_length=100, verbose_name='site name')),
                ('site_description', models.TextField(blank=True, verbose_name='site description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='favicon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='facebook url')),
                ('twitter_url', models.URLField(blank=True, verbose_name='twitter url')),
                ('instagram_url', models.URLField(blank=True, verbose_name='instagram url')),
                ('youtube_url', models.URLField(blank=True, verbose_name='youtube url')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
