# Generated by Django 5.2.4 on 2025-08-30 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaristaTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('date', models.DateField(verbose_name='training date')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='barista_training_banners/', verbose_name='banner or pullup')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barista Training',
                'verbose_name_plural': 'Barista Trainings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BaristaTrainingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('motivation', models.TextField(blank=True, verbose_name='motivation')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.baristatraining')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barista Training Application',
                'verbose_name_plural': 'Barista Training Applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.DeleteModel(
            name='BaristaTrainee',
        ),
    ]
