# Generated by Django 5.2.4 on 2025-08-30 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_baristatraining_baristatrainingapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baristatrainingapplication',
            name='name',
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='agree_participation',
            field=models.BooleanField(default=False, verbose_name='I agree to participate fully in the training program.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='attended_similar',
            field=models.BooleanField(default=False, verbose_name='Have you attended a similar training before?'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='attended_similar_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='If yes, please specify'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='availability',
            field=models.CharField(blank=True, max_length=100, verbose_name='Availability (days/times)'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='cell',
            field=models.CharField(default='', max_length=50, verbose_name='Cell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='confirm_information',
            field=models.BooleanField(default=False, verbose_name='I confirm that the information provided is true and correct.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='country',
            field=models.CharField(default='Rwanda', max_length=50, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='district',
            field=models.CharField(default='', max_length=50, verbose_name='District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='education_level',
            field=models.CharField(default='', max_length=100, verbose_name='Highest Level of Education Completed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='Emergency Contact Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=30, verbose_name='Emergency Contact Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='emergency_contact_relationship',
            field=models.CharField(default='', max_length=50, verbose_name='Relationship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='expected_skills',
            field=models.TextField(blank=True, verbose_name='What skills or knowledge do you expect to gain?'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='id_number',
            field=models.CharField(default='', max_length=50, verbose_name='National ID / Passport Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=100, verbose_name='Languages Spoken'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='nationality',
            field=models.CharField(default='Rwandan', max_length=50, verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='occupation',
            field=models.CharField(default='', max_length=100, verbose_name='Current Occupation / Employment Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Preferred Training Location'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='province',
            field=models.CharField(default='', max_length=50, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='sector',
            field=models.CharField(default='', max_length=50, verbose_name='Sector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='signature_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='signature_name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name of Applicant (as signature)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='skills_experience',
            field=models.TextField(blank=True, verbose_name='Relevant Skills or Experience'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='special_needs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Special Needs / Disabilities'),
        ),
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='village',
            field=models.CharField(default='', max_length=50, verbose_name='Village'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='motivation',
            field=models.TextField(verbose_name='Why do you want to attend this training?'),
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
