# Generated by Django 5.2.4 on 2025-08-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_remove_baristatrainingapplication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baristatraining',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barista_training/images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='baristatraining',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='barista_training/videos/', verbose_name='video'),
        ),
    ]
