# Generated by Django 5.2.4 on 2025-08-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_baristatraining_image_baristatraining_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (jpg, png, webp, max 5MB)', null=True, upload_to='volunteer_opportunities/images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='volunteer_opportunities/videos/', verbose_name='video'),
        ),
    ]
