# Generated by Django 5.2.4 on 2025-08-31 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_volunteeropportunity_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='areas_of_interest',
            field=models.CharField(default='', max_length=200, verbose_name='Areas of Interest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability',
            field=models.CharField(default='', max_length=100, verbose_name='Availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability_times',
            field=models.CharField(blank=True, max_length=100, verbose_name='Availability Times/Specific Dates'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='country',
            field=models.CharField(default='Rwanda', max_length=50, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='date_of_birth',
            field=models.DateField(default='2020-01-01', verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='declaration',
            field=models.BooleanField(default=False, verbose_name='I confirm that the above information is true and complete.'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='Emergency Contact Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=30, verbose_name='Emergency Contact Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='emergency_contact_relationship',
            field=models.CharField(default='', max_length=50, verbose_name='Relationship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_say', 'Prefer not to say')], default='', max_length=20, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='id_number',
            field=models.CharField(default='', max_length=50, verbose_name='National ID/Passport No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='motivation',
            field=models.TextField(default='', verbose_name='Why do you want to volunteer with us?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='other_interest',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Area of Interest'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='province_district',
            field=models.CharField(default='', max_length=100, verbose_name='Province/District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='reference_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference Phone/Email'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference Name'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='reference_relationship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference Relationship'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='sector_cell_village',
            field=models.CharField(default='', max_length=100, verbose_name='Sector/Cell/Village'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='signature_date',
            field=models.DateField(default='2020-01-01', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='signature_name',
            field=models.CharField(default='', max_length=100, verbose_name='Signature (Full Name)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='skills_experience',
            field=models.TextField(blank=True, verbose_name='Relevant Skills & Experience'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
