# Generated by Django 5.2.4 on 2025-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_remove_volunteerapplication_areas_of_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
