# Generated by Django 5.2.4 on 2025-08-31 17:38

import volunteers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_alter_baristatrainingapplication_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='signature_date',
            field=models.DateField(blank=True, default=volunteers.models.today_date, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='signature_date',
            field=models.DateField(blank=True, default=volunteers.models.today_date, null=True, verbose_name='Date'),
        ),
    ]
