# Generated by Django 5.2.4 on 2025-08-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_alter_baristatrainingapplication_signature_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='reference_contact',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='reference_relationship',
        ),
    ]
