# Generated by Django 5.2.5 on 2025-09-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0014_alter_baristatraining_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baristatrainingapplication',
            name='selected_for_training',
            field=models.BooleanField(default=False, help_text='Mark as selected to start training', verbose_name='Selected for Training'),
        ),
    ]
