# Generated by Django 5.2.6 on 2025-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0015_baristatrainingapplication_selected_for_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='occupation',
            field=models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], max_length=20, verbose_name='Current Occupation / Employment Status'),
        ),
    ]
