# Generated by Django 5.2.6 on 2025-09-29 10:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0018_alter_baristatrainingapplication_skills_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='motivation',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Why do you want to attend this training?'),
        ),
    ]
