# Generated by Django 5.2.6 on 2025-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0019_alter_baristatrainingapplication_motivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='expected_skills',
            field=models.TextField(blank=True, verbose_name='What skills or knowledge do you expect to gain?'),
        ),
        migrations.AlterField(
            model_name='baristatrainingapplication',
            name='motivation',
            field=models.TextField(blank=True, verbose_name='Why do you want to attend this training?'),
        ),
    ]
