# Generated by Django 4.2.7 on 2025-07-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=100, verbose_name='stat name')),
                ('stat_value', models.IntegerField(verbose_name='stat value')),
                ('stat_icon', models.CharField(blank=True, max_length=50, verbose_name='stat icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Impact Stat',
                'verbose_name_plural': 'Impact Stats',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='photo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
