# Generated by Django 5.2.4 on 2025-08-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video testimonial (mp4, mov, webm, max 50MB)', null=True, upload_to='testimonials/videos/', verbose_name='video'),
        ),
    ]
