# Generated by Django 5.2.5 on 2025-09-02 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_testimonial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
    ]
