# Generated by Django 5.2.4 on 2025-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_rw',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_rw',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_rw',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
