# Generated by Django 5.2.5 on 2025-09-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_content_alter_blogpost_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_rw',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_rw',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='description_rw',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_rw',
        ),
    ]
