# Generated by Django 5.2.6 on 2025-10-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogcategory_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pinned', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin this post to keep it at the top', verbose_name='pinned'),
        ),
    ]
