# Generated by Django 5.2.4 on 2025-08-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_message_en_contact_message_fr_and_more'),
        ('farmers', '0006_farmer_created_at_farmer_updated_at_and_more'),
        ('trees', '0002_tree_latitude_tree_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100, verbose_name='Donor Name')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Donor Email')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (RWF)')),
                ('donation_type', models.CharField(choices=[('general', 'General Initiative Support'), ('tree', 'Sponsor a Coffee Tree'), ('tour', 'Tourism Experience')], max_length=10, verbose_name='Donation Type')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('payment_status', models.CharField(default='pending', max_length=20, verbose_name='Payment Status')),
                ('receipt_sent', models.BooleanField(default=False, verbose_name='Receipt Sent')),
                ('farmer', models.ForeignKey(blank=True, help_text='If supporting a farmer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.farmer')),
                ('tree', models.ForeignKey(blank=True, help_text='If sponsoring a tree', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.tree')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
