# Generated by Django 5.2.5 on 2025-09-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donation_communication_opt_in_donation_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message_fr',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message_rw',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject_fr',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject_rw',
        ),
    ]
