# Generated by Django 4.2.7 on 2025-07-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='ReusableCupCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_types', models.TextField(verbose_name='cup types')),
                ('incentives', models.TextField(verbose_name='incentives')),
                ('distribution_points', models.TextField(verbose_name='distribution points')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reusable_cup_campaign', to='programs.program')),
            ],
            options={
                'verbose_name': 'Reusable Cup Campaign',
                'verbose_name_plural': 'Reusable Cup Campaigns',
            },
        ),
        migrations.CreateModel(
            name='FarmerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(verbose_name='services')),
                ('distribution_centers', models.TextField(verbose_name='distribution centers')),
                ('training_topics', models.TextField(verbose_name='training topics')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_support', to='programs.program')),
            ],
            options={
                'verbose_name': 'Farmer Support',
                'verbose_name_plural': 'Farmer Supports',
            },
        ),
        migrations.CreateModel(
            name='BaristaTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.TextField(verbose_name='locations')),
                ('duration', models.CharField(max_length=50, verbose_name='duration')),
                ('curriculum', models.TextField(verbose_name='curriculum')),
                ('scholarship_available', models.BooleanField(default=True, verbose_name='scholarship available')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barista_training', to='programs.program')),
            ],
            options={
                'verbose_name': 'Barista Training',
                'verbose_name_plural': 'Barista Trainings',
            },
        ),
    ]
