# Generated by Django 5.2.4 on 2025-08-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmersupport',
            name='program',
        ),
        migrations.RemoveField(
            model_name='reusablecupcampaign',
            name='program',
        ),
        migrations.DeleteModel(
            name='BaristaTraining',
        ),
        migrations.DeleteModel(
            name='FarmerSupport',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ReusableCupCampaign',
        ),
    ]
