# Generated by Django 5.2.6 on 2025-12-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_stock_publicly',
            field=models.BooleanField(default=False, help_text='Display stock quantity on public product pages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, help_text='Available stock quantity (leave empty if not tracking)', null=True),
        ),
    ]
