# Generated by Django 4.2.7 on 2025-07-30 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='farm size (hectares)')),
                ('joined_date', models.DateField(verbose_name='joined date')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farmers/', verbose_name='photo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
        ),
        migrations.CreateModel(
            name='FarmerStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farmer_stories/', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farmer Story',
                'verbose_name_plural': 'Farmer Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
