# Generated by Django 5.2.4 on 2025-08-29 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farmer_age_farmer_avg_monthly_income_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='chronic_illness_details',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('diabetes', 'Diabetes'), ('hiv', 'HIV/AIDS'), ('disability', 'Disability'), ('other', 'Other')], max_length=100, verbose_name='Chronic illness/disability details'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='food_shortage_when',
            field=models.CharField(blank=True, choices=[('dry_season', 'Dry Season'), ('rainy_season', 'Rainy Season'), ('other', 'Other')], max_length=100, verbose_name='If yes, when?'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='main_staple_foods',
            field=models.CharField(blank=True, choices=[('maize', 'Maize'), ('beans', 'Beans'), ('cassava', 'Cassava'), ('rice', 'Rice'), ('other', 'Other')], max_length=100, verbose_name='Main staple foods'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='occupation',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('teacher', 'Teacher'), ('trader', 'Trader'), ('other', 'Other')], max_length=100, verbose_name='Occupation/Income Source'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='sector_district',
            field=models.CharField(choices=[('sector1', 'Sector 1'), ('sector2', 'Sector 2'), ('sector3', 'Sector 3')], max_length=100, verbose_name='Sector/District'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='support_details',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('govt', 'Government'), ('ngo', 'NGO'), ('community', 'Community'), ('other', 'Other')], max_length=100, verbose_name='Support details'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village_cell',
            field=models.CharField(choices=[('village1', 'Village 1'), ('village2', 'Village 2'), ('village3', 'Village 3')], max_length=100, verbose_name='Village/Cell'),
        ),
    ]
