# Generated by Django 5.2.4 on 2025-08-30 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_farmer_created_at_farmer_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmersupportactivity',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Farmer Support Activity', 'verbose_name_plural': 'Farmer Support Activities'},
        ),
        migrations.RemoveField(
            model_name='farmersupportactivity',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmersupportactivity',
            name='is_successful',
        ),
        migrations.RemoveField(
            model_name='farmersupportactivity',
            name='support_type',
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='activity_type',
            field=models.CharField(choices=[('training', 'Training & Education'), ('input', 'Input Distribution'), ('technical', 'Technical Assistance'), ('market', 'Market Access'), ('financial', 'Financial Support'), ('monitoring', 'Monitoring & Evaluation'), ('community', 'Community Building'), ('health', 'Health & Wellbeing'), ('other', 'Other')], default='None', max_length=20, verbose_name='Activity Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_activities/', verbose_name='Attachment (photo, doc, etc.)'),
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='farmers',
            field=models.ManyToManyField(blank=True, related_name='support_activities', to='farmers.farmer'),
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Show on public site'),
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='outcome',
            field=models.TextField(blank=True, verbose_name='Outcome/Notes'),
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmersupportactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='farmersupportactivity',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farmersupportactivity',
            name='description',
            field=models.TextField(default='None', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmersupportactivity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
