# Generated by Django 5.2.4 on 2025-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0007_alter_farmersupportactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerstory',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='farmer_stories/videos/', verbose_name='video'),
        ),
    ]
