# Generated by Django 5.2.4 on 2025-08-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_farmer_sponsorship_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='sponsorship_is_active',
            field=models.BooleanField(default=True, help_text='Is this farm open for sponsorship?'),
        ),
    ]
