# Generated by Django 5.2.5 on 2025-09-02 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0012_alter_farm_description_alter_farmer_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmersupportactivity',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='farmersupportactivity',
            name='outcome',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Outcome/Notes'),
        ),
    ]
