# Generated by Django 5.2.5 on 2025-09-02 06:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_alter_farmersupportactivity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Farm size (hectares)'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is featured'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='joined_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joined date'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='farmerstory',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='farmerstory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='farmerstory',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='farmerstory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_stories/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='farmerstory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='farmerstory',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='farmer_stories/videos/', verbose_name='Video'),
        ),
    ]
