# Generated by Django 5.2.6 on 2025-10-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0015_remove_farmer_sector_district_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['-pinned'], 'verbose_name': 'Farmer', 'verbose_name_plural': 'Farmers'},
        ),
        migrations.AddField(
            model_name='farmer',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin this farmer to keep them at the top', verbose_name='Pinned'),
        ),
    ]
