# Generated by Django 5.2.6 on 2025-12-17 04:40

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Research Category',
                'verbose_name_plural': 'Research Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Research Subscriber',
                'verbose_name_plural': 'Research Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('summary', ckeditor.fields.RichTextField(blank=True, verbose_name='Summary')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author(s)')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('document', models.FileField(blank=True, null=True, upload_to='research_documents/', verbose_name='Document (PDF, DOC, etc.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_images/', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active/Visible')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='researchhub.researchcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Research Publication',
                'verbose_name_plural': 'Research Publications',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reason', ckeditor.fields.RichTextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='researchhub.researchpublication')),
            ],
            options={
                'verbose_name': 'Publication Download Request',
                'verbose_name_plural': 'Publication Download Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
