# Generated by Django 5.2.4 on 2025-09-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub', '0002_researchcategory_researchpublication_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='researchhub.researchpublication')),
            ],
            options={
                'verbose_name': 'Publication Download Request',
                'verbose_name_plural': 'Publication Download Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
