# Generated by Django for Newsletter image field
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter_images/', verbose_name='image'),
        ),
    ]
