# Generated by Django 5.2.4 on 2025-08-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_id'),
        ('newsletter', '0003_newsletter_image'),
    ]

    operations = [
    ]
