# Generated by Django 5.2.6 on 2025-09-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_tree_planted_by_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='planted_by_name',
        ),
        migrations.AlterField(
            model_name='tree',
            name='planted_by',
            field=models.CharField(blank=True, default='None', max_length=128, verbose_name='Planted By'),
            preserve_default=False,
        ),
    ]
