# Generated by Django 5.2.4 on 2025-08-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='program',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a short video (mp4, mov, webm, max 50MB)', null=True, upload_to='programs/videos/', verbose_name='video'),
        ),
    ]
