# Generated by Django 5.2.6 on 2025-12-17 04:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Motivation')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('partner_type', models.CharField(choices=[('corporate', 'Corporate'), ('ngo', 'NGO'), ('government', 'Government'), ('individual', 'Individual')], max_length=20, verbose_name='partner type')),
                ('contact_person', models.CharField(max_length=100, verbose_name='contact person')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='logo')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='joined date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='InitiativeJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_as', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization/Company')], max_length=20, verbose_name='Joining As')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province/State')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sector')),
                ('cell', models.CharField(blank=True, max_length=100, verbose_name='Cell')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village')),
                ('how_heard', models.CharField(blank=True, max_length=100, verbose_name='How did you hear about us?')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='Nationality')),
                ('national_id', models.CharField(blank=True, max_length=16, verbose_name='National ID/Passport Number')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation/Profession')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='volunteers/photos/', verbose_name='Profile Photo')),
                ('org_name', models.CharField(blank=True, max_length=200, verbose_name='Organization/Company Name')),
                ('org_registration', models.CharField(blank=True, max_length=50, verbose_name='Registration Number')),
                ('org_type', models.CharField(blank=True, max_length=50, verbose_name='Organization Type')),
                ('org_contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person Name')),
                ('org_website', models.URLField(blank=True, verbose_name='Website')),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Logo')),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose/Role')),
                ('skills', ckeditor.fields.RichTextField(blank=True, verbose_name='Skills')),
                ('interests', ckeditor.fields.RichTextField(blank=True, verbose_name='Areas of Interest')),
                ('availability', models.CharField(blank=True, max_length=100, verbose_name='Availability')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Sponsorship Amount')),
                ('preferred_location', models.CharField(blank=True, max_length=100, verbose_name='Preferred Location')),
                ('dedication_message', models.CharField(blank=True, max_length=255, verbose_name='Dedication Message')),
                ('area_of_expertise', models.CharField(blank=True, max_length=100, verbose_name='Area of Expertise')),
                ('willing_to_mentor', models.BooleanField(default=False, verbose_name='Willing to Mentor')),
                ('resources_to_offer', ckeditor.fields.RichTextField(blank=True, verbose_name='Resources to Offer')),
                ('barista_experience', models.TextField(blank=True, verbose_name='Barista Experience')),
                ('preferred_training', models.CharField(blank=True, max_length=100, verbose_name='Preferred Training')),
                ('consent', models.BooleanField(default=False, verbose_name='I agree to the terms and privacy policy')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('motivation', models.ManyToManyField(blank=True, related_name='initiative_joins', to='get_involved.motivation', verbose_name='Motivation/Why do you want to join?')),
            ],
            options={
                'verbose_name': 'Initiative Join',
                'verbose_name_plural': 'Initiative Joins',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
