# Generated by Django 4.2.7 on 2025-07-30 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('partner_type', models.CharField(choices=[('corporate', 'Corporate'), ('ngo', 'NGO'), ('government', 'Government'), ('individual', 'Individual')], max_length=20, verbose_name='partner type')),
                ('contact_person', models.CharField(max_length=100, verbose_name='contact person')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='logo')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='joined date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, verbose_name='skills')),
                ('availability', models.CharField(blank=True, max_length=100, verbose_name='availability')),
                ('interests', models.TextField(blank=True, verbose_name='interests')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='joined date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('donation_date', models.DateTimeField(auto_now_add=True, verbose_name='donation date')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='is recurring')),
                ('payment_method', models.CharField(max_length=50, verbose_name='payment method')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-donation_date'],
            },
        ),
    ]
