# Generated by Django to remove the obsolete Donation model from get_involved app
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0002_alter_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
