# Generated by Django 5.2.6 on 2025-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0008_alter_initiativejoin_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Motivation')),
            ],
        ),
        migrations.AlterField(
            model_name='initiativejoin',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Sponsorship Amount'),
        ),
        migrations.RemoveField(
            model_name='initiativejoin',
            name='motivation',
        ),
        migrations.AddField(
            model_name='initiativejoin',
            name='motivation',
            field=models.ManyToManyField(blank=True, related_name='initiative_joins', to='get_involved.motivation', verbose_name='Motivation/Why do you want to join?'),
        ),
    ]
