# Generated by Django 5.2.4 on 2025-09-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author(s)')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('document', models.FileField(blank=True, null=True, upload_to='research_documents/', verbose_name='Document (PDF, DOC, etc.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_images/', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active/Visible')),
            ],
            options={
                'verbose_name': 'Research Publication',
                'verbose_name_plural': 'Research Publications',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
