# Generated by Django 5.2.5 on 2025-09-01 17:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub', '0003_publicationdownloadrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Summary'),
        ),
    ]
