# Generated by Django 5.2.5 on 2025-09-02 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub', '0004_alter_researchcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationdownloadrequest',
            name='reason',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
