# Generated by Django 5.2.5 on 2025-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub', '0005_alter_publicationdownloadrequest_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Research Subscriber',
                'verbose_name_plural': 'Research Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
