# Generated by Django 5.2.5 on 2025-09-01 17:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Event description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=ckeditor.fields.RichTextField(help_text='Event description', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_fr',
            field=ckeditor.fields.RichTextField(help_text='Event description', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_rw',
            field=ckeditor.fields.RichTextField(help_text='Event description', null=True),
        ),
    ]
