# Generated by Django to add new fields to Volunteer model
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0003_remove_donation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Phone Number', blank=True, default=''),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='motivation',
            field=models.TextField(verbose_name='Why do you want to volunteer?', blank=True, default=''),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='consent',
            field=models.BooleanField(verbose_name='I agree to the terms and conditions', default=False),
        ),
    ]
