# Generated by Django 5.2.4 on 2025-08-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0004_add_fields_to_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='motivation',
            field=models.TextField(blank=True, verbose_name='Why do you want to volunteer?'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
    ]
