# Generated by Django 5.2.4 on 2025-08-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0006_initiativejoin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
