# Generated by Django 5.2.5 on 2025-09-02 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0007_delete_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativejoin',
            name='interests',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Areas of Interest'),
        ),
        migrations.AlterField(
            model_name='initiativejoin',
            name='motivation',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Motivation/Why do you want to join?'),
        ),
        migrations.AlterField(
            model_name='initiativejoin',
            name='resources_to_offer',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Resources to Offer'),
        ),
        migrations.AlterField(
            model_name='initiativejoin',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Skills'),
        ),
    ]
